# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# As MoveIt! does not support jerk limits, the acceleration limits provided here are the highest values that guarantee
# that no jerk limits will be violated. More precisely, applying Euler differentiation in the worst case (from min accel
# to max accel in 1 ms) the acceleration limits are the ones that satisfy
# max_jerk = (max_acceleration - min_acceleration) / 0.001

joint_limits:
  ewellix_lift_lower_to_higher:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.0
  vention_rail_base_to_carriage:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 330.0
    max_position:  6.28319 # URDF
    # max_position:  3.14159 # PickNik UR5e
    max_velocity:  0.18
    # max_velocity:  0.0942478 # 54 degrees
    min_position: -6.28319
    # min_position:  -3.14159 # PickNik UR5e
    max_acceleration: 0.18
    # max_acceleration: 0.0942478 # 54 degrees
  shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 330.0
    max_position:  6.28319
    # max_position:  1.5708 # PickNik UR5e
    max_velocity:  0.18
    # max_velocity:  0.0942478 # 54 degrees
    min_position: -6.28319
    # min_position:  -4.71239 # PickNik UR5e
    max_acceleration: 0.18
    # max_acceleration: 0.0942478 # 54 degrees
  elbow_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    # we artificially limit this joint to half its actual joint position limit
    # to avoid (MoveIt/OMPL) planning problems, as due to the physical
    # construction of the robot, it's impossible to rotate the 'elbow_joint'
    # over more than approx +- 1 pi (the shoulder lift joint gets in the way).
    #
    # This leads to planning problems as the search space will be divided into
    # two sections, with no connections from one to the other.
    #
    # Refer to https://github.com/ros-industrial/universal_robot/issues/265 for
    # more information.
    max_position:  3.14159265
    # max_position:  3.14159 # PickNik UR5e
    max_velocity:  0.3 # 84 degrees
    # max_velocity:  0.146608 # 84 degrees
    min_position: -3.14159265
    # min_position:  -3.14159 # PickNik UR5e
    max_acceleration: 0.3 # 84 degrees
    # max_acceleration: 0.146608 # 84 degrees
  wrist_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position:  6.28319
    # max_position:  3.14159 # PickNik UR5e
    max_velocity:  0.3 # 84 degrees
    # max_velocity:  0.146608 # 84 degrees
    min_position: -6.28319
    # min_position:  -3.14159 # PickNik UR5e
    max_acceleration: 0.3 # 84 degrees
    # max_acceleration: 0.146608 # 84 degrees
  wrist_2_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position:  6.28319
    # max_position:  3.14159 # PickNik UR5e
    max_velocity:  0.3 # 84 degrees
    # max_velocity:  0.146608 # 84 degrees
    min_position: -6.28319
    # min_position:  -3.14159 # PickNik UR5e
    max_acceleration: 0.3 # 84 degrees
    # max_acceleration: 0.146608 # 84 degrees
  wrist_3_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position:  6.28319
    # max_position:  6.28319 # PickNik UR5e
    max_velocity:  0.3 # 84 degrees
    # max_velocity:  0.146608 # 84 degrees
    min_position: -6.28319
    # min_position:  -6.28319 # PickNik UR5e
    max_acceleration: 0.3 # 84 degrees
    # max_acceleration: 0.146608 # 84 degrees
  finger_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 130.0
    max_position:  0.025
    max_velocity:  0.15
    min_position: 0.0
    max_acceleration: 1.0
