/**:
  ros__parameters:
    pid_gains:
      position:
        shoulder_pan_joint:
          p: 8000.0
          i: 0.0
          d: 80.0
          u_clamp_max: 330.0
          u_clamp_min: -330.0
          i_clamp_max: 1000.0
          i_clamp_min: -1000.0
        shoulder_lift_joint:
          p: 6000.0
          i: 0.0
          d: 40.0
          u_clamp_max: 330.0
          u_clamp_min: -330.0
          i_clamp_max: 1000.0
          i_clamp_min: -1000.0
        elbow_joint:
          p: 4000.0
          i: 0.0
          d: 15.0
          u_clamp_max: 150.0
          u_clamp_min: -150.0
          i_clamp_max: 10.0
          i_clamp_min: -10.0
        wrist_1_joint:
          p: 1000.0
          i: 0.0
          d: 1.0
          u_clamp_max: 56.0
          u_clamp_min: -56.0
          i_clamp_max: 1000.0
          i_clamp_min: -1000.0
        wrist_2_joint:
          p: 500.0
          i: 0.0
          d: 1.0
          u_clamp_max: 56.0
          u_clamp_min: -56.0
          i_clamp_max: 1000.0
          i_clamp_min: -1000.0
        wrist_3_joint:
          p: 50.0
          i: 0.0
          d: 0.1
          u_clamp_max: 56.0
          u_clamp_min: -56.0
          i_clamp_max: 1000.0
          i_clamp_min: -1000.0

# Methodology for tuning these gains:
# - Using plotjuggler,
#   - plot velocities for each of the joints
#   - plot references against actual positions for each of the joints
# - command trajectories in free space that use all of the joints
#   - if velocity is incredibly noisy, lower d gain
#   - if motion is very oscillatory, increase d gain, or decrease p gain
#   - if tracking lags behind reference, increase p gain, or decrease d gain
# - test against a full demo that includes object interaction to make sure it is
#   aggressive enough to maintain position in these scenarios.
