# This file is used as a drt_ros2_control_tools/controller_check.py input to define which controller names to highlight
- clr_joint_trajectory_controller
- joint_trajectory_controller
- lift_position_trajectory_controller
- lift_rail_joint_trajectory_controller
- rail_position_trajectory_controller
- robotiq_activation_controller
- robotiq_gripper_hande_controller
- joint_state_broadcaster
- io_and_status_controller
